[package]
name = "learn_tokio"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46.1", features = ["full"] }
tokio-stream = "0.1.17"
mini-redis = "0.4.1"
rand = "0.9.2"
bytes = "1.10.1"
futures = "0.3.31"